### ISSUE TITLE
 Couchbase sorgusunda hata

### ISSUE THREAD

**Issue by altuga** [kodcu/sliconf-micro#2]
Merhaba

Couchbase 'de bahsedilen adımı gerçekleştirirken  :  
SELECT FIRST t FOR t IN hashedPassword WHEN t.a1 = -74 END FROM users WHERE ANY t IN hashedPassword SATISFIES t.a1 = -74 END;

Aşağıdaki hata ile karşılaştım

[
  {
    "code": 4000,
    "msg": "No index available on keyspace users that matches your query. Use CREATE INDEX or CREATE PRIMARY INDEX to create an index, or check that your expected index is online.",
    "query_from_user": "SELECT FIRST t FOR t IN hashedPassword WHEN t.a1 = -74 END FROM users WHERE ANY t IN hashedPassword SATISFIES t.a1 = -74 END;"
  }
]

Şema olmadığı için aldı ama şemayı nasıl yükleyeceğim bilemdim @Taifuru

**Comment by atagulalan** [comment]
Artık **MongoDB** kullanıldığı için kapatıldı.
